85c85
< 	wget --no-check-certificate -nc -O $(SRC_DIR)/srw.zip https://github.com/buzmakov/SRW/archive/feature/srw_lite.zip; echo 'Done'
---
> 	wget --no-check-certificate -nc -O $(SRC_DIR)/srw.zip https://github.com/sergeyyakubov/SRW/archive/openmp.zip; echo 'Done'
88c88
< 	mv $(TMP_DIR)/SRW-feature-srw_lite $(TMP_DIR)/SRW
---
> 	mv $(TMP_DIR)/SRW-openmp $(TMP_DIR)/SRW
